main: co.purevanilla.mcplugins.taxes.Taxes
version: 1.0.0
name: Taxes
author: quiquelhappy
api-version: 1.18
depend:
  - Essentials
  - Gemmy
commands:
  balancetop:
    aliases: [baltop]
    description: shows total points and balance top